apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - image: siva1998/prodapp:latest
        name: prod-app
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "6Gi"
          limits:
            memory: "8Gi"