apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - image: siva1998/prod-app:latest
        name: prod-app
        ports:
        - containerPort: 8080